### ISSUE TITLE
Set the token exponent 

### ISSUE THREAD

**Issue by Palpatin-lll** [forbole/big-dipper-2.0-cosmos#1288]
Hello everyone, I know how to set up the token exponent. BDJuno in the config file.yaml
 ```
tokens:
        - name: Atom
          units:
            - denom: uatom
              exponent: 0
            - denom: atom
              *exponent: 6*
              price_id: cosmos
        - name: Photino
          units:
            - denom: uptn
              exponent: 0
            - denom: ptn
              *exponent: 6*
```
I have a question how to configure the exponent of a token that does not exist at the time of installing the big dipper browser.
