### ISSUE TITLE
Websocket connection fails

### ISSUE THREAD

**Issue by justyntemme** [forbole/big-dipper-2.0-cosmos#693]
When i try and connect the front end to hasura I get an error connecting to the websocket URL. I have tried starting the url with http:// and ws://. I looked and it seems hasura is only listening on 8080 with http. The documentation does not provide an example how to have hasura listen via websockets. 

```
[Error] WebSocket connection to 'ws://localhost:8080/v1/graphql' failed: WebSocket is closed before the connection is established.
```

**Comment by ryuash** [comment]
Websockets are all handled by hasura with no extra setup.

- Have you tried using the actual ip address instead of localhost?
- Does the subscriptions work on the console?
- Are you running both hasura and the ui locally on your own pc?

**Comment by ryuash** [comment]
Okay I was able to reproduce it but can you confirm the web socket really didn't connect after numerous tries?

The error should be from the first try but it connects in the second one:

![image](https://user-images.githubusercontent.com/42913823/153329136-5fea531f-4d34-4172-a440-88751044e483.png)

First: 
![image](https://user-images.githubusercontent.com/42913823/153329234-c49ff19c-2891-4547-9fa1-2c3bad4e21eb.png)

Second:
![image](https://user-images.githubusercontent.com/42913823/153329253-b5af969e-bee3-4757-9c29-f3cb8d313e30.png)

I've looked around and it is an issue with the browser but we've set the ws to keep retrying here so it should not be an issue:

```
const wsLink = new WebSocketLink({
  uri: process.env.NEXT_PUBLIC_GRAPHQL_WS ?? 'wss://localhost:3000',
  options: {
    reconnect: true,
  },
  webSocketImpl: WebSocket,
});
```

**Comment by ryuash** [comment]
The local setup i tried while following the docs also had no data and it connected. 

Since I can't reproduce the error I will provide the steps I took to get it working locally on my local mac env. 

PSQL:
- Just followed the docs and created a database and tables

HASURA:
- Get the docker compose file from the official documentation. Removed the psql service and added the database url (note i'm using `host.docker.internal` because of the local env being on macOS:

```
version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.2.0
    ports:
    - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_DATABASE_URL: postgres://<user>@host.docker.internal:5432/<table>
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: <adminsecret>
```

- inside `bdjuno/hasura` with hasura cli installed run `hasura metadata apply --endpoint "http://localhost:8080/" --admin-secret <adminsecret>`

UI:
- Add the following to `.env`:
```
NEXT_PUBLIC_GRAPHQL_URL=http://localhost:8080/v1/graphql
NEXT_PUBLIC_GRAPHQL_WS=ws://localhost:8080/v1/graphql
xNODE_ENV=production
xPORT=3000
NEXT_PUBLIC_URL=<url>
NEXT_PUBLIC_WS_CHAIN_URL=<rpc websocket>
NEXT_PUBLIC_CHAIN_STATUS=mainnet
```

Start it up and check that it connected inside the console's network tab
