### ISSUE TITLE
I'm unable to see any data after setting up Big Dipper 2.0

### ISSUE THREAD

**Issue by LordXyTh** [forbole/big-dipper-2.0-cosmos#828]
hello,

I have setup big dipper 2.0 and bdjuno. In hasura I can see data being consistently updated in the block table. However, nothing seems to show up in the big dipper ui.

I'm using the latest version of wasmd for my chain

Here's my config.yaml for .bdjuno

```
chain:
    bech32_prefix: vibe
    modules:
      - actions
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://54.149.253.14:26657
            max_connections: 20
        grpc:
            address: 54.149.253.14:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 5s
database:
    name: bdjuno
    host: <removed>
    port: 5432
    user: <removed>
    password: <removed>
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text

actions:
  port: 3000
```
app.toml for chain:

`
halt-height = 0
halt-time = 0
iavl-cache-size = 781250
index-events = []
inter-block-cache = true
min-retain-blocks = 0
minimum-gas-prices = ""
pruning = "default"
pruning-interval = "0"
pruning-keep-every = "0"
pruning-keep-recent = "0"

[api]
  address = "tcp://0.0.0.0:1317"
  enable = true
  enabled-unsafe-cors = true
  max-open-connections = 1000
  rpc-max-body-bytes = 1000000
  rpc-read-timeout = 10
  rpc-write-timeout = 0
  swagger = true

[grpc]
  address = "0.0.0.0:9090"
  enable = true

[grpc-web]
  address = "0.0.0.0:9091"
  enable = true
  enable-unsafe-cors = true

[rosetta]
  address = ":8080"
  blockchain = "app"
  enable = true
  network = "network"
  offline = false
  retries = 3

[rpc]
  cors_allowed_origins = ["*"]

[state-sync]
  snapshot-interval = 0
  snapshot-keep-recent = 2

[telemetry]
  enable-hostname = false
  enable-hostname-label = false
  enable-service-label = false
  enabled = false
  global-labels = []
  prometheus-retention-time = 0
  service-name = ""
`

my chain config

`
{
  "title": "Vibe Block Explorer",
  "network": "vibechain",
  "icon": "https://raw.githubusercontent.com/forbole/big-dipper-assets/master/desmos/icon.svg?sanitize=true",
  "logo": {
    "default": "https://raw.githubusercontent.com/forbole/big-dipper-assets/master/desmos/logo.svg?sanitize=true"
  },
  "prefix": {
    "consensus": "riz",
    "validator": "riz",
    "account": "riz"
  },
  "genesis": {
    "time": "2021-07-13T08:00:00",
    "height": 1
  },
  "primaryTokenUnit": "vibe",
  "votingPowerTokenUnit": "vibe",
  "tokenUnits": {
    "vibe": {
      "display": "vibe",
      "exponent": 6
    }
  },
  "extra": {
    "profile": true
  }
}
`
